### ISSUE TITLE
Add support to Meteor 0.9

### ISSUE THREAD

**Issue by bitomule** [frozeman/meteor-animation-helper-velocity#8]
I'm not sure what's needed to support meteor 0.9 but it would be great :)

**Comment by frozeman** [comment]
i'm on it. i will try to make them work in the next day(s)

**Comment by frozeman** [comment]
ok i did it, can you test and close this issue :)

**Comment by bitomule** [comment]
wow, that was fast!

It's working perfect with native meteor package system.

Thanks @frozeman
